import { Controller, Get, Post, Body, Patch, Param, Delete, ParseUUIDPipe, UseGuards, Request } from '@nestjs/common';
import { ProjectService } from './project.service';
import { CreateProjectDto } from './dto/create-project.dto';
import { UpdateProjectDto } from './dto/update-project.dto';
import { ApiTags, ApiOperation, ApiResponse, ApiParam, ApiBearerAuth } from '@nestjs/swagger';
import { Project } from '@prisma/client'; // Assuming Project type is generated by Prisma
import { JwtAuthGuard } from '../auth/guards/jwt-auth.guard'; // Importar JwtAuthGuard
import { Logger } from '@nestjs/common'; // Import Logger

@ApiTags('Projects')
@Controller('api/projects')
export class ProjectController {
    private readonly logger = new Logger(ProjectController.name); // Add Logger instance

    constructor(private readonly projectService: ProjectService) { }

    @UseGuards(JwtAuthGuard)
    @Get('mine')
    @ApiOperation({ summary: 'Get projects accessible by the current user' })
    @ApiBearerAuth()
    @ApiResponse({ status: 200, description: 'List of user projects.', type: [CreateProjectDto] })
    @ApiResponse({ status: 401, description: 'Unauthorized.' })
    findMine(@Request() req): Promise<Pick<Project, 'id' | 'name'>[]> {
        const userId = req.user.userId;
        const tenantId = req.user.tenantId || req.body.tenantId || req.query.tenantId;
        return this.projectService.findAllForUser(userId, tenantId);
    }

    @Post()
    @ApiOperation({ summary: 'Create a new project' })
    @ApiResponse({ status: 201, description: 'The project has been successfully created.', type: CreateProjectDto })
    @ApiResponse({ status: 400, description: 'Bad Request.' })
    create(@Body() createProjectDto: CreateProjectDto): Promise<Project> {
        this.logger.debug(`[create] Received POST request. Body: ${JSON.stringify(createProjectDto, null, 2)}`);
        return this.projectService.create(createProjectDto);
    }

    @Get()
    @ApiOperation({ summary: 'Get all projects' })
    @ApiResponse({ status: 200, description: 'List of all projects.', type: [CreateProjectDto] })
    findAll(@Request() req): Promise<Project[]> {
        const tenantId = req.user?.tenantId || req.body?.tenantId || req.query?.tenantId;
        return this.projectService.findAll(tenantId);
    }

    @Get(':id')
    @ApiOperation({ summary: 'Get a project by ID' })
    @ApiParam({ name: 'id', description: 'Project CUID', type: String })
    @ApiResponse({ status: 200, description: 'The found project record', type: CreateProjectDto })
    @ApiResponse({ status: 404, description: 'Project not found.' })
    findOne(@Param('id') id: string, @Request() req): Promise<Project> {
        const tenantId = req.user?.tenantId || req.body?.tenantId || req.query?.tenantId;
        return this.projectService.findOne(id, tenantId);
    }

    @Patch(':id')
    @ApiOperation({ summary: 'Update a project by ID' })
    @ApiParam({ name: 'id', description: 'Project CUID', type: String })
    @ApiResponse({ status: 200, description: 'The project has been successfully updated.', type: CreateProjectDto })
    @ApiResponse({ status: 404, description: 'Project not found.' })
    @ApiResponse({ status: 400, description: 'Bad Request.' })
    update(@Param('id') id: string, @Body() updateProjectDto: UpdateProjectDto, @Request() req): Promise<Project> {
        this.logger.debug(`[update] Received PATCH for projectId: ${id}. Body: ${JSON.stringify(updateProjectDto, null, 2)}`);
        const tenantId = req.user?.tenantId || req.body?.tenantId || req.query?.tenantId;
        return this.projectService.update(id, updateProjectDto, tenantId);
    }

    @Delete(':id')
    @ApiOperation({ summary: 'Delete a project by ID' })
    @ApiParam({ name: 'id', description: 'Project CUID', type: String })
    @ApiResponse({ status: 200, description: 'The project has been successfully deleted.', type: CreateProjectDto })
    @ApiResponse({ status: 404, description: 'Project not found.' })
    remove(@Param('id') id: string, @Request() req): Promise<Project> {
        const tenantId = req.user?.tenantId || req.body?.tenantId || req.query?.tenantId;
        return this.projectService.remove(id, tenantId);
    }
} 