import { Controller, Get, Post, Body, Patch, Param, Delete, ParseUUIDPipe, UseGuards, Request } from '@nestjs/common';
import { ProjectService } from './project.service';
import { CreateProjectDto } from './dto/create-project.dto';
import { UpdateProjectDto } from './dto/update-project.dto';
import { ApiTags, ApiOperation, ApiResponse, ApiParam, ApiBearerAuth } from '@nestjs/swagger';
import { Project } from '@prisma/client'; // Assuming Project type is generated by Prisma
import { JwtAuthGuard } from '../auth/guards/jwt-auth.guard'; // Importar JwtAuthGuard

@ApiTags('Projects')
@Controller('projects')
export class ProjectController {
    constructor(private readonly projectService: ProjectService) { }

    @UseGuards(JwtAuthGuard)
    @Get('mine')
    @ApiOperation({ summary: 'Get projects accessible by the current user' })
    @ApiBearerAuth() // Indicar que requiere autenticación JWT
    @ApiResponse({ status: 200, description: 'List of user projects.', type: [CreateProjectDto] }) // Ajustar el DTO si es necesario (solo id y name)
    @ApiResponse({ status: 401, description: 'Unauthorized.' })
    findMine(@Request() req): Promise<Pick<Project, 'id' | 'name'>[]> {
        // req.user es poblado por JwtAuthGuard con el payload del token (ej: { userId: string, email: string })
        const userId = req.user.userId;
        return this.projectService.findAllForUser(userId);
    }

    @Post()
    @ApiOperation({ summary: 'Create a new project' })
    @ApiResponse({ status: 201, description: 'The project has been successfully created.', type: CreateProjectDto }) // Use appropriate type if Project model differs
    @ApiResponse({ status: 400, description: 'Bad Request.' })
    create(@Body() createProjectDto: CreateProjectDto): Promise<Project> {
        return this.projectService.create(createProjectDto);
    }

    @Get()
    @ApiOperation({ summary: 'Get all projects' })
    @ApiResponse({ status: 200, description: 'List of all projects.', type: [CreateProjectDto] }) // Use appropriate type
    findAll(): Promise<Project[]> {
        return this.projectService.findAll();
    }

    @Get(':id')
    @ApiOperation({ summary: 'Get a project by ID' })
    @ApiParam({ name: 'id', description: 'Project CUID', type: String })
    @ApiResponse({ status: 200, description: 'The found project record', type: CreateProjectDto }) // Use appropriate type
    @ApiResponse({ status: 404, description: 'Project not found.' })
    findOne(@Param('id') id: string): Promise<Project> { // No ParseUUIDPipe as ID is CUID (string)
        return this.projectService.findOne(id);
    }

    @Patch(':id')
    @ApiOperation({ summary: 'Update a project by ID' })
    @ApiParam({ name: 'id', description: 'Project CUID', type: String })
    @ApiResponse({ status: 200, description: 'The project has been successfully updated.', type: CreateProjectDto }) // Use appropriate type
    @ApiResponse({ status: 404, description: 'Project not found.' })
    @ApiResponse({ status: 400, description: 'Bad Request.' })
    update(@Param('id') id: string, @Body() updateProjectDto: UpdateProjectDto): Promise<Project> {
        return this.projectService.update(id, updateProjectDto);
    }

    @Delete(':id')
    @ApiOperation({ summary: 'Delete a project by ID' })
    @ApiParam({ name: 'id', description: 'Project CUID', type: String })
    @ApiResponse({ status: 200, description: 'The project has been successfully deleted.', type: CreateProjectDto }) // Use appropriate type
    @ApiResponse({ status: 404, description: 'Project not found.' })
    remove(@Param('id') id: string): Promise<Project> {
        return this.projectService.remove(id);
    }
} 